name: Build and Run Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: dtrochow/3-key:v0.0.1

    steps:
    - name: Checkout repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Build Unit Tests
      working-directory: tests
      run: |
        mkdir build
        cd build
        cmake ..
        make -j8

    - name: Run Unit Tests
      working-directory: tests/build
      run: |
        ctest --output-on-failure

    - name: Upload test logs
      if: failure()
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
      with:
        name: test-logs
        path: tests/build/Testing/Temporary/LastTest.log
